#!/bin/sh
alias ls="eza --icons --group --all --sort=modified --reverse --classify --binary --time-style=long-iso --colour-scale=all"
alias tree="tree -L 3 --gitignore -C"
alias grep="grep --color=auto"
alias mv='mv --no-clobber'
alias cp='cp --no-clobber'
alias df='df -hT'
alias :q="exit"
alias :e="vim"

alias conf='function _(){ $EDITOR ${XDG_CONFIG_HOME}/$1; }; _'
alias sconf='function _(){ doas $EDITOR /etc/$1; }; _'
alias ip="ip -c"
alias diff='diff --color -W $(( $(tput cols) - 2 ))'

alias nvim="TERM=xterm-256color nvim"
alias svim="doas vim -u ~/.config/vim/init.vim"
alias nowlmode="export QT_QPA_PLATFORM=xcb && unset WAYLAND_DISPLAY"
alias tmate='tmate -f ~/.config/tmate/config '
alias gcalcli='gcalcli --config-folder=~/.config/gcalcli '
alias agenda="gcalcli --calendar=rolferen@gmail.com --calendar=Learnist agenda '$(date)' '$(date --date='next month')'"
alias no='yes "n"'
alias ntpdate='echo "doas ntpdate no.pool.ntp.org"; doas ntpdate no.pool.ntp.org; echo "doas hwclock --systohc"; doas hwclock --systohc; :'
alias tail='tail -n69 '
alias doas='doas env '
alias doass='doas'

# alias python='/usr/bin/python -q '
alias rg='rg --max-columns-preview'

mount() {
	command mount "$@" | bat -l mount --style=plain
}

hi () {
	emulate -L zsh

	argv=(${argv:/-s/-S})
	argv=(${argv:/-l/-S})

	autoload -U colors && colors
	for file do
		echoti setaf 247
		printf "%*s\n" "$(( ${COLUMNS:-$(tput cols)} - 6))" '' | sed 's/ /▁/g'
		printf '%s %s\n' '▏' "${file}"
		printf "%*s\n" "$(( ${COLUMNS:-$(tput cols)} - 6))" '' | sed 's/ /▔/g'
		highlight -O truecolor --force --stdout "$file"
	done
}

# vim: ts=4 sts=4 sw=4 noexpandtab

