#!/bin/sh

# Session XDG specification
export XDG_SESSION_TYPE="wayland"
export XDG_SESSION_DESKTOP="sway"
export XDG_CURRENT_DESTKOP="sway"
export DESKTOP_SESSION="sway"

# XKB
export XKB_DEFAULT_LAYOUT=us

export LIBSEAT_BACKEND="logind"

# QT
export QT_WAYLAND_DISABLE_WINDOW_DECORATION=1
export QT_QPA_PLATFORM="wayland-egl"

# GTK
export GDK_BACKEND="wayland,x11"
export GTK_BACKEND="wayland"

# XWayland
export DISPLAY=":0"

# Other stuff
export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland"


# DRM
export WLR_DRM_DEVICES=/dev/dri/card0


export EDITOR=nvim

# XDG Base directory fixes for pseudo-compatible programs
export SSB_HOME="$XDG_DATA_HOME"/zoom
export SWAY_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/sway"
# x11
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
# postgresql
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_CACHE_HOME/pg/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"
# pass
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export MPLAYER_HOME="$XDG_CONFIG_HOME"/mplayer
# Golang
export GOPATH="$XDG_DATA_HOME"/go
export FFMPEG_DATADIR="$XDG_CONFIG_HOME"/ffmpeg
export BASH_COMPLETION_USER_FILE="$XDG_CONFIG_HOME"/bash-completion/bash_completion
# coreutils
eval $(dircolors "$XDG_CONFIG_HOME"/dircolors)

