#!/bin/sh

# XDG Base directory fixes for pseudo-compatible programs
export SSB_HOME="${XDG_DATA_HOME}/zoom"
export SWAY_CONFIG_HOME="${XDG_CONFIG_HOME}/sway"
export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
# postgresql
export PSQLRC="${XDG_CONFIG_HOME/pg/psqlrc}"
export PSQL_HISTORY="${XDG_CACHE_HOME/pg/psql_history}"
export PGPASSFILE="${XDG_CONFIG_HOME/pg/pgpass}"
export PGSERVICEFILE="${XDG_CONFIG_HOME/pg/pg_service.conf}"
# pass
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/pass"
export MPLAYER_HOME="${XDG_CONFIG_HOME}/mplayer"
export FFMPEG_DATADIR="${XDG_CONFIG_HOME}/ffmpeg"
export BASH_COMPLETION_USER_FILE="${XDG_CONFIG_HOME}/bash-completion/bash_completion"
# gnupg
export GNUPGHOME=${XDG_DATA_HOME}/gnupg
export LESSHISTFILE=${XDG_STATE_HOME}/less/history

# wget-hsts for tracking downloaded files, defaults to $HOME/.wget-hsts. dumb
export WGETRC=${XDG_CONFIG_HOME}/wget/config

# default applications
export EDITOR=nvim
export MANPAGER="nvim -R -c 'set ft=man'"
export GITPAGER="nvim -R -c 'set ft=man' -c 'set ft=git'"  # i'm not really sure what causes the need to first set ft=man and then ft=git, but this way we avoid \[033; errors

# Python
export PYTHONSTARTUP=${XDG_CONFIG_HOME}/python/pythonrc

# Rust
export CARGO_HOME=${XDG_DATA_HOME}/cargo
# Golang
export GOPATH="${XDG_DATA_HOME}/go"

# Move Perl out of home
PERL_BASE="$HOME/.local/share/perl"
export PERL_MM_OPT="INSTALL_BASE=$PERL_BASE"
export PERL_MB_OPT="--install_base $PERL_BASE"
export PATH="$PERL_BASE/bin${PATH:+:$PATH}"
export PERL5LIB="$PERL_BASE/lib/perl5"
export MANPATH="$PERL_BASE/man${MANPATH:+:$MANPATH}"

# PATHS
export PATH="$XDG_DATA_HOME/gem/ruby/2.6.0/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/gits/bin:$PATH"
export PATH="./build/:$PATH"
export PATH="./bin/:$PATH"
export PATH=".:$PATH"
export PATH=$(lspaths | cat -n | sort -k2 -k1n | uniq -f1 | sort -nk1,1 | cut -f2- | sed -e :a -e '$!N; s/\n/:/; ta')


export LANG="en_US.UTF-8"


