#!/bin/sh

# Session XDG specification
export XDG_SESSION_TYPE="wayland"
export XDG_SESSION_DESKTOP="sway"
export XDG_CURRENT_DESTKOP="sway"
export DESKTOP_SESSION="sway"

# XKB
export XKB_DEFAULT_LAYOUT=us

export LIBSEAT_BACKEND="logind"

# QT
export QT_WAYLAND_DISABLE_WINDOW_DECORATION=1
export QT_QPA_PLATFORM="wayland-egl"

# GTK
export GDK_BACKEND="wayland,x11"
export GTK_BACKEND="wayland"

# XWayland
export DISPLAY=":0"

# Other stuff
export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland"

export VK_ICD_FILENAMES=/opt/amdgpu/etc/vulkan/icd.d/amd_icd64.json

# DRM
export WLR_DRM_DEVICES=/dev/dri/card0


