#!/bin/sh

# Session XDG specification
export XDG_SESSION_TYPE="wayland"
export XDG_SESSION_DESKTOP="sway"
export XDG_CURRENT_DESTKOP="sway"
export DESKTOP_SESSION="sway"

# XKB
export XKB_DEFAULT_LAYOUT=us

export LIBSEAT_BACKEND="seatd"
export ALSOFT_DRIVERS="pipewire"

# QT
export QT_WAYLAND_DISABLE_WINDOW_DECORATION=1
export QT_QPA_PLATFORM="wayland-egl"
# export QT_QPA_PLATFORM_PLUGIN_PATH="~/.local/share/miniconda3/plugins/platforms/"

# GTK
export GDK_BACKEND="wayland,x11"
export GTK_BACKEND="wayland"

# XWayland
# export DISPLAY=":0"

# Other stuff
export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland"

# Vulkan
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
# export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json


# DRM
export WLR_DRM_DEVICES=/dev/dri/card0


# AT-SPI2 is a little meanie miney mo
export NO_AT_BRIDGE=1

