#!/bin/sh

# Session XDG specification
export XDG_SESSION_TYPE="wayland"
export XDG_SESSION_DESKTOP="sway"
export XDG_CURRENT_DESTKOP="sway"
export DESKTOP_SESSION="sway"

# XKB
export XKB_DEFAULT_LAYOUT=us

export LIBSEAT_BACKEND="seatd"
export ALSOFT_DRIVERS="pipewire"

# QT
export QT_WAYLAND_DISABLE_WINDOW_DECORATION=1
export QT_QPA_PLATFORM="wayland-egl"

# GTK
export GDK_BACKEND="wayland,x11"
export GTK_BACKEND="wayland"

# XWayland
export DISPLAY=":0"

# Other stuff
export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland"

# DRM
export WLR_DRM_DEVICES=/dev/dri/card0

# AT-SPI2 is a little meanie miney mo
export NO_AT_BRIDGE=1
